# Languages
#   Create a `[X]` block for each language you want, where X is the language ID.
#   Refer to https://sourcethemes.com/academic/docs/language/

# Configure the English version of the site.
[en]
  languageCode = "en-gb"
  contentDir = "content/en"  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.

# Uncomment the lines below to configure your website in a second language.
[ja]
  languageCode = "ja-jp"
  contentDir = "content/ja"
  title = "日本ワイワム"
  [ja.params]
#    description = "Site description in Japanese..."
  [[ja.menu.main]]
    name = "について"
    url = "#about"
    weight = 10
