# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Explore"
  url = "#explore"
  weight = 10

[[main]]
  name = "Discipleship Training School"
  url = "/dts"
  weight = 20

[[main]]
  name = "Get Involved"
  url = "/get-involved"
  weight = 30

[[main]]
  name = "Who We Are"
  url = "/about"
  weight = 40

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
